import type { LucideIcon } from "lucide-react";
import {
  AppWindow,
  Bird,
  Box,
  Boxes,
  Brackets,
  Braces,
  Circle,
  CircleDot,
  Cloud,
  Code,
  Code2,
  Coffee,
  Cog,
  Compass,
  Container,
  Database,
  Droplet,
  FileCode,
  Film,
  Gem,
  GitBranch,
  Hexagon,
  Layers,
  Moon,
  Package,
  Search,
  Shield,
  Terminal,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * 工具名 → lucide 图标映射。
 * 找不到匹配时回退到 Box（通用工具箱）。
 */
export const TOOL_ICONS: Record<string, LucideIcon> = {
  node: Braces,
  bun: Zap,
  deno: Shield,
  python: Code2,
  java: Coffee,
  openjdk: Coffee,
  temurin: Coffee,
  ruby: Gem,
  go: Hexagon,
  rust: Cog,
  dotnet: AppWindow,
  maven: Package,
  gradle: Boxes,
  pnpm: Layers,
  npm: Box,
  yarn: Circle,
  terraform: Cloud,
  kubernetes: Compass,
  docker: Container,
  php: FileCode,
  lua: Moon,
  kotlin: Code,
  elixir: Droplet,
  clojure: Brackets,
  julia: CircleDot,
  swift: Bird,
  zig: Zap,
  postgres: Database,
  mysql: Database,
  sqlite: Database,
  redis: Database,
  mongodb: Database,
  git: GitBranch,
  gh: Terminal,
  ripgrep: Search,
  ffmpeg: Film,
  imagemagick: Wrench,
};

export function toolIcon(name: string): LucideIcon {
  return TOOL_ICONS[name.toLowerCase()] || Box;
}
